name: project_w
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  file_picker: ^4.0.0
  path_provider: ^2.0.5
  animated_text_kit: ^4.2.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/layout1.png
   - assets/images/layout2.png
   - assets/images/layout3.png
   - assets/images/layout4.png
  